version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - backend/.env
    ports:
      - "5000:5000"
    command: npm run dev
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_API_BASE=http://localhost:5000
    ports:
      - "5173:80"
    depends_on:
      - backend
